---
- name: Testing andrewrothstein.pandoc
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'pandoc --version'
      ansible.builtin.command: /usr/local/bin/pandoc --version
      changed_when: false
      register: pandoc_test_output
    - name: Output of 'pandoc --version'
      ansible.builtin.debug:
        msg: '{{ pandoc_test_output.stdout }} '
